services:
  github-runner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      RUNNER_REPOSITORY_URL: ${RUNNER_REPOSITORY_URL?RUNNER_REPOSITORY_URL is required}
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN?GITHUB_ACCESS_TOKEN is required}
      RUNNER_NAME: "docker-self-hosted-runner"
      RUNNER_LABELS: "docker,linux,self-hosted,freebsd"
      RUNNER_WORK_DIRECTORY: "/runner/_work"
      RUNNER_GROUP: "default"
      RUNNER_WORKDIR: "/runner/work"
      LIBVIRT_DEFAULT_URI: "qemu:///system"
    privileged: true
    security_opt:
      - seccomp=unconfined
    cap_add:
      - ALL
    cgroup: host
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/runner
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - libvirt_qemu:/var/lib/libvirt/qemu
      - libvirt_images:/var/lib/libvirt/images
      - qemu_logs:/var/log/qemu
      - libvirt_logs:/var/log/libvirt
      - freebsd_vm_data:/runner/_work/_actions/vmactions/freebsd-vm/v1
      - /lib/modules:/lib/modules:ro
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    extra_hosts:
      - "freebsd:127.0.0.1"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  runner_data:
  libvirt_qemu:
  libvirt_images:
  qemu_logs:
  libvirt_logs:
  freebsd_vm_data:
    driver: local